/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as InvoiceRouteImport } from './invoice'
import { Route as SleepRouteRouteImport } from './sleep/route'
import { Route as IndexRouteImport } from './index'
import { Route as SleepIndexRouteImport } from './sleep/index'
import { Route as SleepSettingsRouteImport } from './sleep/settings'
import { Route as SleepPlayerRouteImport } from './sleep/player'
import { Route as SleepListRouteImport } from './sleep/list'

const InvoiceRoute = InvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepRouteRoute = SleepRouteRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepIndexRoute = SleepIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SleepRouteRoute,
} as any)
const SleepSettingsRoute = SleepSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SleepRouteRoute,
} as any)
const SleepPlayerRoute = SleepPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => SleepRouteRoute,
} as any)
const SleepListRoute = SleepListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => SleepRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sleep': typeof SleepRouteRouteWithChildren
  '/invoice': typeof InvoiceRoute
  '/sleep/list': typeof SleepListRoute
  '/sleep/player': typeof SleepPlayerRoute
  '/sleep/settings': typeof SleepSettingsRoute
  '/sleep/': typeof SleepIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invoice': typeof InvoiceRoute
  '/sleep/list': typeof SleepListRoute
  '/sleep/player': typeof SleepPlayerRoute
  '/sleep/settings': typeof SleepSettingsRoute
  '/sleep': typeof SleepIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sleep': typeof SleepRouteRouteWithChildren
  '/invoice': typeof InvoiceRoute
  '/sleep/list': typeof SleepListRoute
  '/sleep/player': typeof SleepPlayerRoute
  '/sleep/settings': typeof SleepSettingsRoute
  '/sleep/': typeof SleepIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sleep'
    | '/invoice'
    | '/sleep/list'
    | '/sleep/player'
    | '/sleep/settings'
    | '/sleep/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invoice'
    | '/sleep/list'
    | '/sleep/player'
    | '/sleep/settings'
    | '/sleep'
  id:
    | '__root__'
    | '/'
    | '/sleep'
    | '/invoice'
    | '/sleep/list'
    | '/sleep/player'
    | '/sleep/settings'
    | '/sleep/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SleepRouteRoute: typeof SleepRouteRouteWithChildren
  InvoiceRoute: typeof InvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep/': {
      id: '/sleep/'
      path: '/'
      fullPath: '/sleep/'
      preLoaderRoute: typeof SleepIndexRouteImport
      parentRoute: typeof SleepRouteRoute
    }
    '/sleep/settings': {
      id: '/sleep/settings'
      path: '/settings'
      fullPath: '/sleep/settings'
      preLoaderRoute: typeof SleepSettingsRouteImport
      parentRoute: typeof SleepRouteRoute
    }
    '/sleep/player': {
      id: '/sleep/player'
      path: '/player'
      fullPath: '/sleep/player'
      preLoaderRoute: typeof SleepPlayerRouteImport
      parentRoute: typeof SleepRouteRoute
    }
    '/sleep/list': {
      id: '/sleep/list'
      path: '/list'
      fullPath: '/sleep/list'
      preLoaderRoute: typeof SleepListRouteImport
      parentRoute: typeof SleepRouteRoute
    }
  }
}

interface SleepRouteRouteChildren {
  SleepListRoute: typeof SleepListRoute
  SleepPlayerRoute: typeof SleepPlayerRoute
  SleepSettingsRoute: typeof SleepSettingsRoute
  SleepIndexRoute: typeof SleepIndexRoute
}

const SleepRouteRouteChildren: SleepRouteRouteChildren = {
  SleepListRoute: SleepListRoute,
  SleepPlayerRoute: SleepPlayerRoute,
  SleepSettingsRoute: SleepSettingsRoute,
  SleepIndexRoute: SleepIndexRoute,
}

const SleepRouteRouteWithChildren = SleepRouteRoute._addFileChildren(
  SleepRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SleepRouteRoute: SleepRouteRouteWithChildren,
  InvoiceRoute: InvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
