export const zhCN = {
  app: {
    title: '家用陪伴站',
    subtitle: '给家里人一个更省心的夜间播放工具',
  },
  common: {
    backHome: '返回首页',
    confirm: '确认',
    cancel: '取消',
    retry: '重新播放',
    loading: '正在加载',
    empty: '暂时还没有内容',
  },
  home: {
    heroTitle: '把常用功能放到一个清爽入口',
    heroDescription: '优先照顾老人使用习惯，字更大、按钮更清楚、操作路径更短。',
    switchToDark: '切换深色背景',
    switchToLight: '切换浅色背景',
    sleepTitle: '哄睡歌曲',
    sleepDescription: '打开就能直接播放，支持暂停、切歌、定时停止和离线缓存。',
    sleepAction: '进入哄睡歌曲',
    resumeLastSong: '继续上次播放',
    invoiceTitle: '发票打印',
    invoiceDescription: '这一块先预留入口，后面再逐步补功能。',
    invoiceAction: '查看占位页',
    invoiceComingSoon: '建设中',
  },
  nav: {
    player: '当前播放',
    list: '歌曲列表',
    settings: '播放设置',
  },
  sleep: {
    moduleTitle: '哄睡歌曲',
    moduleTip: '为家里人准备的简洁播放页',
    play: '播放',
    pause: '暂停',
    resume: '继续播放',
    stop: '停止',
    prev: '上一曲',
    next: '下一曲',
    loop: '单曲循环',
    single: '单曲播放',
    sequence: '顺序播放',
    shuffle: '随机播放',
    timer: '定时停止',
    timerOff: '关闭定时',
    timerMinutes: '分钟后停止',
    timerRunning: '剩余 {{minutes}} 分 {{seconds}} 秒',
    songList: '歌曲列表',
    settings: '播放设置',
    noSong: '还没有可播放的歌曲',
    noSongTip: '请先把歌曲文件和歌单配置放到静态资源目录。',
    continueLast: '继续播放上次歌曲',
    currentSong: '当前歌曲',
    progress: '播放进度',
    searchPlaceholder: '搜索歌曲名、别名或标签',
    currentPlaying: '正在播放',
    loadingCatalog: '正在读取歌单',
    loadFailed: '歌单读取失败',
    modeTitle: '播放模式',
    themeTitle: '主题模式',
    themeAuto: '自动',
    themeLight: '浅色',
    themeDark: '深色',
    cacheTitle: '离线内容',
    cacheStart: '一键离线',
    cacheClear: '清除离线内容',
    cacheReady: '离线内容已准备好',
    cacheHint: '建议在 Wi-Fi 下使用，避免额外流量。',
    cacheUpdate: '歌单已更新，请重新下载离线内容。',
    cacheProgress: '离线缓存进度 {{progress}}%',
    compatibilityTitle: '兼容性说明',
    compatibilityBody: '在 iPhone 上，系统可能不会完全遵守网页里的音量上限设置，请留意设备音量。',
    mediaError: '当前歌曲暂时无法播放，请稍后重试。',
    offlineError: '离线缓存有部分资源没有成功，请稍后再试。',
  },
  invoice: {
    title: '发票打印',
    description: '这里先保留一个入口页，后续再补打印表单和模板。',
    badge: '建设中',
  },
} as const

export function formatCopy(template: string, vars: Record<string, string | number>) {
  return Object.entries(vars).reduce((result, [key, value]) => {
    return result.replace(`{{${key}}}`, String(value))
  }, template)
}
